version: '3'
services:
  database:
    image: 'postgres:latest'
    ports:
      - "2001:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: default_database
    expose:
      - 2001

  axon:
    image: axoniq/axonserver
    environment:
      - SPRING_SERVLET_MULTIPART_MAX-FILE-SIZE=20MB
      - SPRING_SERVLET_MULTIPART_MAX-REQUEST-SIZE=20MB
      - AXONIQ_AXONSERVER_DEVMODE_ENABLED=TRUE

    ports:
      - '8024:8024'
      - '8124:8124'
      - '8224:8224'
    container_name: 'axon_server'


  application:
    depends_on:
      - database
      - axon
    image: panusdx/investment
    ports:
      - "1973:1973"
    container_name: 'java_app'
    expose:
      - 1973
    environment:
      spring.datasource.url: jdbc:postgresql://host.docker.internal:2001/default_database
      axoniq.axonserver.hostname: host.docker.internal
      logging.file: messaging.log
      logging.path: /var/log


