version: '3'
services:
  database:
    image: 'postgres:latest'
    ports:
      - "2001:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: default_database
    expose:
      - 2001







  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbit'
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - 5672



  application:
    depends_on:
      - database
      - rabbitmq
    image: panusdx/investment
    ports:
      - "1973:1973"
    container_name: 'java_app'
    expose:
      - 1973
    environment:
      spring.datasource.url: jdbc:postgresql://host.docker.internal:2001/default_database
      spring.rabbitmq.host: host.docker.internal


networks:
  rabbitmq_go_net:
    driver: bridge



